### ISSUE TITLE
Fix Mahmoud issues 

### ISSUE THREAD

**Issue by MahmoudMH** [gazaskygeeks/FAC-jobs-platform#45]
there is some issues to fix it, with Mahmoud

**Comment by astroash** [comment]
@MahmoudMH can you give more description?

- what are the issues
- what files/pages are they on

**Comment by MahmoudMH** [comment]
when I review back in detail the details, I found a lot of none clean code some bugs in the database: 
we will fix it later so no one worries about it it's like best practice and clean code, again it's like best practice and none clean code !!! 

src/server/inde.js | 27 | URL should not be hardcoded
src/server/inde.js | 33 | what should function done do?
src/server/inde.js | 75 | what is this ????
src/server/inde.js | 78 | MAX AGE 1000 month ???!!???
src/server/inde.js | 97 | middleware should be re-arranged
src/server/controllers | N\A | controller name should have Controller postfix
N\A | N\A | you should follow js variables naming convention ( camel case)
N\A | N\A | you should follow js functions naming convention ( camel case)
src/server/controllers/routes.js | 15 | using arrow function ( mixing ES6 with ES5)?
src/server/contorllers/routes.js | 16 | admin Added' should not be hard-coded, do the same for later if statement
src/server/contorllers/routes.js | 22 | URL should not be hardcoded
src/server/contorllers/routes.js | N\A | you may separate auth routes in a separate file
src/server/controllers/ | N\A | files names should be declarative
src/server/models/database/build.sql | 9 | email is not UNIQUE? username too?
src/server/models/database/build.sql | 9 | email VARCHAR(300) ?? too large
src/server/models/database/build.sql | 10 | avatar VARCHAR(8000) ??? too large
src/server/models/database/build.sql | 13 | is admin ?? why how many admins do you have?
src/server/models/database/build.sql | 8 | username TEXT type ?? how long should the username be
src/server/models/database/build.sql | 24 | skills TEXT[] ????????
src/server/models/database/build.sql | N\A | this file has to be completely re-written
src/server/models/ | N\A | database folder should be renamed into migrations also seeds should be extracted away
src/client/index.js | 4 | import browser router as Router ( just a convention)
src/client/reducers | N\A | use declarative names for reducers
src/client/reducers | N\A | follow files naming convention
src/client/reducers | N\A | I think you have to ask someone about an initial state for multiple reducers, I am not sure about that

**Comment by astroash** [comment]
@MahmoudMH thank you for the update. Remember that issues should be written so that they can be understood by anyone else in the team, not just reminders for yourself.
